<?php

if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

return array(
	'name'                    => __( 'EASL Table of Content', 'total-child' ),
	'base'                    => 'easl_table_of_content',
	'icon'                    => 'vcex-icon ticon ticon-list-alt',
	'is_container'            => false,
	'show_settings_on_create' => true,
	'category'                => __( 'EASL', 'total-child' ),
	'description'             => __( 'Add a callout section with button.', 'total-child' ),
	'php_class_name'          => 'EASL_VC_Table_Of_Content',
	'params'                  => array(
		array(
			'type'        => 'textfield',
			'heading'     => __( 'Widget Heading', 'total-child' ),
			'param_name'  => 'heading',
			'admin_label' => true,
		),
		array(
			'type'        => 'dropdown',
			'heading'     => __( 'Display Type', 'total-child' ),
			'param_name'  => 'display_type',
			'admin_label' => false,
			'value'       => array(
				'Inline' => '',
				'List'   => 'list',
			),
		),
		array(
			'type'       => 'param_group',
			'heading'    => __( 'Items', 'total-child' ),
			'param_name' => 'items',
			'group'      => __( 'Items', 'total-child' ),
			'value'      => urlencode( json_encode( array(
				array(
					'i_title'  => '',
					'i_target' => ''
				),
			) ) ),
			'params'     => array(
				array(
					'type'        => 'textfield',
					'value'       => '',
					'param_name'  => 'i_title',
					'heading'     => __( 'Title', 'total-child' ),
					'admin_label' => true,
				),
				array(
					'type'        => 'textfield',
					'value'       => '',
					'param_name'  => 'i_target',
					'heading'     => __( 'Target ID', 'total-child' ),
					'admin_label' => false,
				),
			),
		),
        
        array(
            'type'       => 'vcex_ofswitch',
            'heading'    => __( 'Enable sticky on scroll', 'total-child' ),
            'param_name' => 'sticky_on_scroll',
            'std'        => 'false',
            'admin_label' => false,
            'group'       => __( 'Sticky on Scroll', 'total-child' ),
        ),
        array(
            'type'        => 'dropdown',
            'heading'     => __( 'Sticky Type', 'total-child' ),
            'param_name'  => 'sticky_type',
            'value'       => array(
                __( 'Bellow Header Navigation', 'total-child' ) => '',
                __( 'Body Left', 'total-child' )   => 'left',
            ),
            'dependency'  => array(
                'element' => 'sticky_on_scroll',
                'value'   => array( 'true' ),
            ),
            'std'         => '',
            'admin_label' => false,
            'group'       => __( 'Sticky on Scroll', 'total-child' ),
            'description' => __( 'The body left option will only work for screen size greater than 1560px.', 'js_composer' ),
        ),
		array(
			'type'        => 'el_id',
			'heading'     => __( 'Element ID', 'js_composer' ),
			'param_name'  => 'el_id',
			'admin_label' => false,
			'description' => sprintf( __( 'Enter element ID (Note: make sure it is unique and valid according to <a href="%s" target="_blank">w3c specification</a>).', 'js_composer' ), 'http://www.w3schools.com/tags/att_global_id.asp' ),
		),
		array(
			'type'        => 'textfield',
			'heading'     => __( 'Extra class name', 'js_composer' ),
			'param_name'  => 'el_class',
			'admin_label' => false,
			'description' => __( 'Style particular content element differently - add a class name and refer to it in custom CSS.', 'js_composer' ),
		),
        array(
            'type'        => 'dropdown',
            'heading'     => __( 'Font size', 'total-child' ),
            'param_name'  => 'item_font_size',
            'admin_label' => false,
            'group'       => __( 'Item Design option', 'total-child' ),
            'value'       => array(
                __( 'Default', 'total-child' ) => '',
                __( '12px', 'total-child' ) => '12',
                __( '13px', 'total-child' ) => '13',
                __( '14px', 'total-child' ) => '14',
                __( '15px', 'total-child' ) => '15',
                __( '16px', 'total-child' ) => '16',
                __( '17px', 'total-child' ) => '17',
                __( '18px', 'total-child' ) => '18',
                __( '19px', 'total-child' ) => '19',
                __( '20px', 'total-child' ) => '20',
                __( '21px', 'total-child' ) => '21',
                __( '22px', 'total-child' ) => '22',
                __( '23px', 'total-child' ) => '23',
                __( '24px', 'total-child' ) => '24',
            ),
        ),
        array(
            'type'        => 'dropdown',
            'heading'     => __( 'Font weight', 'total-child' ),
            'param_name'  => 'item_font_weight',
            'admin_label' => false,
            'group'       => __( 'Item Design option', 'total-child' ),
            'value'       => array(
                __( 'Default', 'total-child' ) => '',
                __( 'Normal', 'total-child' ) => 'normal',
                __( 'Lighter', 'total-child' ) => 'lighter',
                __( 'Bold', 'total-child' ) => 'bold',
            ),
        ),
        array(
            'type'        => 'dropdown',
            'heading'     => __( 'Font style', 'total-child' ),
            'param_name'  => 'item_font_style',
            'admin_label' => false,
            'group'       => __( 'Item Design option', 'total-child' ),
            'value'       => array(
                __( 'Default', 'total-child' ) => '',
                __( 'Normal', 'total-child' ) => 'normal',
                __( 'Italic', 'total-child' ) => 'italic',
            ),
        ),
        array(
            'type'        => 'dropdown',
            'heading'     => __( 'Background Colour', 'total-child' ),
            'param_name'  => 'item_bg_color',
            'admin_label' => false,
            'group'       => __( 'Item Design option', 'total-child' ),
            'value' => array(
                __( 'Default', 'total-child' ) => '',
                __('Primary(Blue)', 'total-child') => 'primary',
                __('Secondary(Light Blue)', 'total-child') => 'secondary',
                __('Red', 'total-child') => 'red',
                __('Teal', 'total-child') => 'teal',
                __('Orange', 'total-child') => 'orange',
                __('Grey', 'total-child') => 'grey',
                __('Yellow', 'total-child') => 'yellow',
                __('White', 'total-child') => 'white',
            ),
        ),
        array(
            'type'        => 'dropdown',
            'heading'     => __( 'Border Colour', 'total-child' ),
            'param_name'  => 'item_border_color',
            'admin_label' => false,
            'group'       => __( 'Item Design option', 'total-child' ),
            'value' => array(
                __( 'Default', 'total-child' ) => '',
                __('Primary(Blue)', 'total-child') => 'primary',
                __('Secondary(Light Blue)', 'total-child') => 'secondary',
                __('Red', 'total-child') => 'red',
                __('Teal', 'total-child') => 'teal',
                __('Orange', 'total-child') => 'orange',
                __('Grey', 'total-child') => 'grey',
                __('Yellow', 'total-child') => 'yellow',
                __('White', 'total-child') => 'white',
            ),
        ),
        array(
            'type'        => 'dropdown',
            'heading'     => __( 'Shape', 'total-child' ),
            'param_name'  => 'item_shape',
            'admin_label' => false,
            'group'       => __( 'Item Design option', 'total-child' ),
            'value'       => array(
                __( 'Default', 'total-child' ) => '',
                __( 'Rectangular', 'total-child' ) => 'rect',
                __( 'Rounded', 'total-child' ) => 'rounded',
                __( 'Rounded - Large', 'total-child' ) => 'rounded_large',
            ),
        ),
		array(
			'type'        => 'css_editor',
			'heading'     => __( 'CSS box', 'js_composer' ),
			'param_name'  => 'css',
			'admin_label' => false,
			'group'       => __( 'Container Design option', 'js_composer' ),
		),
	),
);
